[package]
name = "rust_http_request"
version = "0.1.0"
authors = ["Hoomweb <analitico01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
reqwest = "0.11.2"
